learning_blog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls', namespace='users')),
    path('', include('learning_blogs.urls', namespace='learning_blogs')),

]

learning_blogs/urls.py
"""define url mode of learning_logs"""

from django.urls import path,re_path
# . indicates Django imports views from the current directory
from . import views

urlpatterns = [
    # home
    path('', views.index, name='index'),
    # topics
    path('topics/', views.topics, name='topics'),
    # specified topic detail
    re_path('topics/(?P<topic_id>\d+)/', views.topic, name='topic'),
    # web page used to add new topics
    path('new_topic/', views.new_topic, name='new_topic'),
    # web page used to add new entries
    re_path('new_entry/(?P<topic_id>\d+)/', views.new_entry, name='new_entry'),
    re_path('edit_entry/(?P<entry_id>\d+)/', views.edit_entry, name='edit_entry'),
]
app_name = 'learning_blogs'

users/urls.py
#from django.conf.urls import url
from django.urls import path
from django.contrib.auth.views import login

from . import views

urlpatterns=[
    #login page
    path('login/',login, {'template_name':'users/login.html'}, name='login'),
    # 注销
    path('logout/', views.logout_view, name='logout'),
    # 注册页面
    path('register/', views.register, name='register'),
]
app_name = 'users'

learning_blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.text

class Entry(models.Model):
    """主题的具体知识"""
    #topic = models.ForeignKey(Topic)
    topic=models.ForeignKey('Topic', on_delete=models.CASCADE)
    text=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural='entries'

    def _str_(self):
        """返回模型的字符串表示"""
        return self.text

users/models.py
from django.db import models

# Create your models here.

learning_blogs/forms.py
from django import forms
# 从models.py导入Topic类
from .models import Topic, Entry

class TopicForm(forms.ModelForm): # TopicForm继承forms.ModelForm
    class Meta:
        model = Topic # 根据模型Topic创建表单model
        fields = ['text'] # 表单只包含text字段
        labels = {'text': ''} # 不要为labels生成标签

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_blogs/views.py
from django.shortcuts import render
from .models import Topic,Entry
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404

# Create your views here.
def index(request):
    """  首页 """
    return render(request, 'learning_blogs/index.html')

@login_required
def topics(request):
    '''显示所有的主题'''
    topics=Topic.objects.filter(owner=request.user).order_by('date_added')
    context={'topics':topics}
    return render(request,'learning_blogs/topics.html',context)

@login_required
def topic(request, topic_id):
    """显示单个主题及其所有的条目"""
    topic = Topic.objects.get(id=topic_id)
    # 确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404
    # minus sign indicates descending sort
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_blogs/topic.html', context)

@login_required
def new_topic(request):
    """添加主题"""
    if request.method != 'POST':
        # didn't submit data: create a new form
        form = TopicForm # TopicForm is imported from ./form.py
    else:
        # data submitted through post: process the data
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            #form.save()
            # redirect user to topics page 将用户重定向到主题页
            return HttpResponseRedirect(reverse('learning_blogs:topics'))

    context = {'form': form}
    return render(request, 'learning_blogs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """add a new entry in a specific topic 在特定主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        # no data submitted; create a new form
        form = EntryForm()
    else:
        # data submitted through post; process data
        form = EntryForm(data=request.POST)
        if form.is_valid():
            # create a new entry instance,
            # and store it in new_entry, but not in database yet(commit=False)
            new_entry = form.save(commit=False)
            # add topic attr & set it
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(
                reverse('learning_blogs:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_blogs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """edit an existing entry"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    # 确认请求的主题属于当前用户
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # first request; fill the form with old info
        form = EntryForm(instance=entry)
    else:
        # POST request; process the data
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(
                reverse('learning_blogs:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_blogs/edit_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
#from django.core.urlresolvers import reverse
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
# Create your views here.




def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_blogs:index'))


def register(request):
    """注册新用户"""
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录，再重定向到主页
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('learning_blogs:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

learning_blogs/templates/learning_blogs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>日常</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>
<!-- 静态导航 -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
            </button>
            <a class="navbar-brand" href="{% url 'learning_blogs:index' %}">首页</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'learning_blogs:topics' %}">主题</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a>你好, {{ user.username }}.</a></li>
                    <li><a href="{% url 'users:logout' %}">注销</a></li>
                {% else %}
                    <li><a href="{% url 'users:register' %}">注册</a></li>
                    <li><a href="{% url 'users:login' %}">登录</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse  导航折叠;  -->
    </div>
</nav>
<div class="container">
    <div class="page-header">
        {% block header %}{% endblock header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</div> <!-- /container 容器 -->
</body>
</html>

learning_blogs/templates/learning_blogs/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>编辑内容</title>
</head>
<body>
{% extends "learning_blogs/base.html" %}
{% block content %}
    <p><a href="{% url 'learning_blogs:topic' topic.id %}">{{ topic }}</a></p>
    <p>编辑:</p>
    <form action="{% url 'learning_blogs:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">保存</button>
    </form>
{% endblock content %}
</body>
</html>

learning_blogs/templates/learning_blogs/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>日常--个人成长记录</title>
</head>
<body>

{% extends "learning_blogs/base.html" %}

{% block header %}
    <div class='jumbotron'>
        <h1 style="color:DarkOrange">日常,记录你的每一天.</h1>
    </div>
{% endblock header %}

{% block content %}
    <h2>
        <a href="{% url 'users:register' %}">注册账户</a>
    </h2>
    <h2>
        这里是你的个人成长记录，请写下标题.
    </h2>
    <h2>
        无论是生活,工作,还是学习，请写下主要内容.
    </h2>
{% endblock content %}

</body>
</html>

learning_blogs/templates/learning_blogs/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>内容</title>
</head>
<body>
{% extends "learning_blogs/base.html" %}

{% block content %}
    <p><a href="{% url 'learning_blogs:topic' topic.id %}">{{ topic }}</a></p>
    <p>添加:</p>
    <form action="{% url 'learning_blogs:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">添加</button>
    </form>
{% endblock content %}
</body>
</html>

learning_blogs/templates/learning_blogs/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>新主题</title>
</head>
<body>
{% extends "learning_blogs/base.html" %}

{% load bootstrap3 %}
{% block header %}
    <h2>添加主题:</h2>
{% endblock header %}

{% block content %}
    <p>添加:</p>
    <form action="{% url 'learning_blogs:new_topic' %}" method="post" class="form">
        {% csrf_token %}
        <!--{{ form.as_p }}-->
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">添加</button>
        {% endbuttons %}
    </form>

{% endblock content %}
</body>
</html>

learning_blogs/templates/learning_blogs/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主题</title>
</head>
<body>
{% extends 'learning_blogs/base.html' %}

{% block header %}
    <h1 style="color:DarkOrange">日常</h1>
{% endblock header %}


{% block content %}
    <h3>{{ topic }}</h3>
    <p></p>
    <p>
        <a href="{% url 'learning_blogs:new_entry' topic.id %}">添加</a>
    </p>

    {% for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    {{ entry.date_added|date:'M d, Y H:i' }}
                    <small>
                        <a href="{% url 'learning_blogs:edit_entry' entry.id %}">
                            编辑</a>
                    </small>
                </h3>
            </div>
            <div class="panel-body">
                {{ entry.text|linebreaks }}
            </div>
        </div> <!-- panel -->
    {% empty %}
        还没有录入内容
    {% endfor %}

{% endblock content %}
</body>
</html>

learning_blogs/templates/learning_blogs/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>主题</title>
</head>
<body>
{% extends "learning_blogs/base.html" %}

{% block header %}
    <h1 style="color:DarkOrange">日常</h1>
{% endblock header %}


{% block content %}
    <p></p>
    <ul>
        {% for topic in topics %}
            <li>
                <h3>
                    <a href="{% url 'learning_blogs:topic' topic.id %}">{{ topic }}</a>
                </h3>
            </li>
        {% empty %}
            <li>还没有添加主题</li>
        {% endfor %}
    </ul>
    <h3><a href="{% url 'learning_blogs:new_topic' %}">添加主题:</a></h3>
{% endblock content %}
</body>
</html>

users/templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录页面</title>
</head>
<body>

{% extends "learning_blogs/base.html" %}

{% load bootstrap3 %}
{% block header %}
    <h2>请使用您的账户登录.</h2>
{% endblock header %}

{% block content %}

    {% if form.errors %}
        <p>您输入的用户名和密码不匹配，请重新输入!</p>
    {% endif %}

    <form method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}
        <!--{{ form.as_p }}-->
        {% bootstrap_form form %}

        {% buttons %}
            <button name="submit" class="btn btn-primary">登录</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'learning_blogs:index' %}"/>
    </form>
{% endblock content %}

</body>
</html>

users/templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
</head>
<body>

{% extends "learning_blogs/base.html" %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">
      {% csrf_token %}
      {{ form.as_p }}

      <button name="submit">注册</button>
      <input type="hidden" name="next" value="{% url 'learning_blogs:index' %}" />
  </form>

{% endblock content %}

</body>
</html>